sap_hypervisor_node_preconfigure: Added OCP Auth, replaced oc wait with k8s native function
sap-linuxlab/community.sap_infrastructure pull request #44
Opened 2024-06-26 13:19 UTC by newkit

- Added authentication via kubeconfig, kubeadmin & password. Need to provide ca-cert too in order to validate connection.
- The oc wait commands have been replaced with a k8s native function.
- Do not download virtctl to the jumphost anylonger.
- Housekeeping: removed unused kargs.yml.

This includes a better version as used in this [PR](https://github.com/sap-linuxlab/community.sap_infrastructure/pull/7) and therefore makes it obsolete.

2024-06-26 15:29 UTC, newkit commented
@0xFelix could you please review? Sorry for the extra loop.

2024-07-01 16:33 UTC, sean-freeman requested changes

2024-07-01 16:33 UTC, sean-freeman commented on roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/install-sriov-operator.yml
> +- name: Enable unsupported NICs for SRIOV usage
Typo, `SR-IOV`

2024-07-02 15:51 UTC, newkit commented on playbooks/sample-sap-hypervisor-redhat-ocp-virt-preconfigure.yml
>      sap_hypervisor_node_platform: redhat_ocp_virt
@sean-freeman I am confused, I see `sap_hypervisor_node_preconfigure_platform` nowhere defined, only  `sap_hypervisor_node_platform`. Do you mean to replace all occurencies of `sap_hypervisor_node_platform` with `sap_hypervisor_node_preconfigure_platform`? Please elaborate.

2024-07-02 15:54 UTC, newkit commented on playbooks/sample-sap-hypervisor-redhat-ocp-virt-preconfigure.yml
> +      register: __sap_vm_provision_register_ocp_auth_results
By space you mean newline? 

Login and receiving API Key is not optional but required on OCPv.

2024-07-02 15:56 UTC, newkit commented on requirements.yml
> +  - name: community.general
`community.okd` and  therefore `community.general` is required by the ` community.okd.openshift_auth` call in playbook `playbooks/sample-sap-hypervisor-redhat-ocp-virt-preconfigure.yml`.

2024-07-03 10:55 UTC, sean-freeman commented on playbooks/sample-sap-hypervisor-redhat-ocp-virt-preconfigure.yml
>      sap_hypervisor_node_platform: redhat_ocp_virt
Yes, var should be amended to the correct prefix

2024-07-03 10:56 UTC, sean-freeman commented on playbooks/sample-sap-hypervisor-redhat-ocp-virt-preconfigure.yml
> +      register: __sap_vm_provision_register_ocp_auth_results
Yes, newline.

Both username/password and API Key are required?  That seems highly ineffective/inefficient, will not question further though

2024-07-03 10:57 UTC, sean-freeman commented on requirements.yml
> +  - name: community.general
`community.okd.openshift_auth` has a dependency on `community.general`? That's not pretty but I'll consider this closed in that case

2024-07-08 13:10 UTC, newkit commented on roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/install-sriov-operator.yml
> +- name: Enable unsupported NICs for SRIOV usage
Ack, will be fixed.

2024-07-08 13:10 UTC, newkit commented on roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/configure-worker-node.yml
> +      status: True
Ack, will be fixed.

2024-07-08 13:10 UTC, newkit commented on roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/configure-worker-node.yml
> +    wait: yes
Ack, will be fixed.

2024-08-06 09:11 UTC, newkit commented
I believe I've resolved all the mentioned issues, could you please take a look @sean-freeman ?

2024-08-22 15:06 UTC, rhmk approved these changes
The requested changes were made and they LGTM

2024-08-22 15:41 UTC, merged