sap_vm_provision: exec flow amendments from testing
sap-linuxlab/community.sap_infrastructure pull request #58
Opened 2024-08-30 10:54 UTC by sean-freeman

sap_vm_provision: exec flow amendments from testing

2024-09-02 07:48 UTC, marcelmamula approved these changes
LGTM after connectivity typo is resolved @sean-freeman I suppose removal of AWS and GCP from Readme is because Ansible collections are used instead of CLI, right?

2024-09-12 12:44 UTC, berndfinger commented
> LGTM after connectivity typo is resolved @sean-freeman I suppose removal of AWS and GCP from Readme is because Ansible collections are used instead of CLI, right?

@marcelmamula As there has been no reply yet from @sean-freeman, should we just assume that the answer to your question is `yes`, and just merge and fix the spelling error and the ansible-lint error in a new small PR right after merging?

2024-09-12 13:12 UTC, Wabri requested changes
Minor linting problem to fix

2024-09-12 13:12 UTC, Wabri commented on roles/sap_vm_provision/tasks/platform_ansible/ibmcloud_powervs/execute_main.yml
> +    # required for both outbound Public Internet connectivty and internal traffic to other IBM Cloud Services
```suggestion
    # required for both outbound Public Internet connectivity and internal traffic to other IBM Cloud Services
```

2024-09-12 13:12 UTC, Wabri commented on roles/sap_vm_provision/tasks/platform_ansible/ibmcloud_vs/execute_setup_ha.yml
```suggestion
```

Too many blank line => https://github.com/sap-linuxlab/community.sap_infrastructure/actions/runs/10631453083/job/29472374510?pr=58

2024-09-13 08:20 UTC, merged